twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    globals:
        Menus: "@Site.Configuration"
        UserNotification: "@User.Notification"
when@test:
    twig:
        strict_variables: true
